name: poker_client
description: 德州扑克远程对战安卓客户端（虚拟积分娱乐场）
publish_to: 'none'
version: 0.0.20+20

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/app_icon.png
    - images/avatars/
